basePath: /
definitions:
  handlers.LoginRequest:
    description: Login credentials structure
    properties:
      login:
        example: doctor_ivanov
        type: string
      password:
        example: securepassword123
        type: string
    required:
    - login
    - password
    type: object
  models.Doctor:
    description: Medical professional information
    properties:
      created_at:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      login:
        type: string
      middle_name:
        type: string
      password_hash:
        type: string
      specialization:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: your@email.com
    name: API Support
  description: This is a sample server for mobile application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: MobileApp API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login with login and password
      parameters:
      - description: Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login a doctor
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Register a new doctor with the input payload
      parameters:
      - description: Doctor information
        in: body
        name: doctor
        required: true
        schema:
          $ref: '#/definitions/models.Doctor'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Doctor'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new doctor
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
